common/models/Client.php
<?php
namespace common\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * Client model
 *
 * @property integer $client_id
 * @property string $first_name
 * @property string $last_name
 * @property string $address
 * @property string $email
 * @property string $phone
 * @property integer $created_at
 * @property integer $updated_at
 */
class Client extends ActiveRecord
{
    /**
     * @return array
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'phone', 'email', 'address'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'client';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getLoyaltyCards()
    {
        return $this->hasMany(LoyaltyCard::className(), ['client_id' => 'client_id']);
    }
}

backend/controllers/ClientController.php
<?php
namespace backend\controllers;

use backend\models\AddClientForm;
use backend\models\ClientSearch;
use common\models\Client;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'add', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \Exception
     */
    public function actionAdd()
    {
        $model = new AddClientForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->addClient()) {
            Yii::$app->session->setFlash('success', 'Client saved successfully');
            return $this->redirect(['index']);
        }

        return $this->render('add', [
            'model' => $model
        ]);
    }


    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        if (!($client = Client::findOne($id)) || !$client->delete()) {
            throw new \Exception('Error deleting client');
        }
        Yii::$app->session->setFlash('success', 'Successfully deleted');
        return $this->redirect(['index']);
    }
}

backend/controllers/LoyaltyCardController.php
<?php
namespace backend\controllers;

use backend\models\AddLoyaltyCardForm;
use backend\models\LoyaltyCardSearch;
use common\models\LoyaltyCard;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class LoyaltyCardController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'edit', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new LoyaltyCardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param integer $id
     * @return string|\yii\web\Response
     * @throws \Exception
     */
    public function actionEdit($id = null)
    {
        $model = new AddLoyaltyCardForm(['id' => $id]);
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->addCard()) {
            Yii::$app->session->setFlash('success', 'Card saved successfully');
            return $this->redirect(['index']);
        }

        return $this->render('edit', [
            'model' => $model
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        if (!($card = LoyaltyCard::findOne($id)) || !$card->delete()) {
            throw new \Exception('Error deleting loyalty card');
        }
        Yii::$app->session->setFlash('success', 'Successfully deleted');
        return $this->redirect(['index']);
    }
}

backend/views/client/add.php
<?php

use common\models\LoyaltyCard;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>


<div>
    <div class="row">
        <?php $form = ActiveForm::begin(); ?>
        <div class="col-lg-5">
            <h1>Add client</h1>
            <?= $form->field($model, 'firstName')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'lastName')->textInput() ?>

            <?= $form->field($model, 'address')->textInput() ?>

            <?= $form->field($model, 'email')->textInput() ?>

            <?= $form->field($model, 'phone')->textInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
        <div class="col-lg-5">
            <h1>Add loyalty card</h1>

            <?= $form->field($model, 'cardNumber')->textInput(['placeholder' => 'Select card number or it will be set automatically']) ?>

            <?= $form->field($model, 'cardType')->dropDownList(LoyaltyCard::getCardTypes(), ['prompt' => '-----']) ?>

        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/client/index.php
<?php

/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel \backend\models\ClientSearch */

use common\models\LoyaltyCard;
use yii\grid\GridView;
use yii\helpers\Html;

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        'client_id',
        'first_name',
        'last_name',
        'address',
        'email',
        'phone',
        [
            'attribute' => 'card_number',
            'label' => 'Loyalty cards',
            'value' => function ($model) {
                $links = '';
                foreach ($model->loyaltyCards as $loyaltyCard) {
                    /** @var LoyaltyCard $loyaltyCard */
                    $links .= Html::a($loyaltyCard->card_number, ['loyalty-card/index', 'LoyaltyCardSearch[card_number]' => $loyaltyCard->card_number]) . '<br>';
                }
                return $links;
            },
            'format' => 'raw'
        ],
        'created_at:datetime',
        'updated_at:datetime',
        [
            'class' => \yii\grid\ActionColumn::className(),
            'template'=>'{delete}',
        ]
    ]
]);